const wildersList = [
	{
		img: "./public/img/img-wilders/alexandre.jpg",
		firstname: "Alexandre",
		lastname: "HIANCE",
		desc: "La meilleure façon de produire l'avenir est de le créer. - A. Lincoln",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "alexandrehiance@gmail.com",
		github: "https://github.com/Alexhian",
		linkedin: "https://www.linkedin.com/in/alexandre-hiance-111718151/",
	},
	{
		img: "./public/img/img-wilders/maxime.png",
		firstname: "Maxime",
		lastname: "TRICOCHE",
		desc: "Persévérant et curieux, je suis toujours désireux d'acquérir de nouvelles compétences",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "maxime.trche@gmail.com",
		github: "https://github.com/maximetricoche",
		linkedin: "https://www.linkedin.com/in/maxime-tricoche-a85142310/",
	},
	{
		img: "./public/img/img-wilders/sabrina.jpg",
		firstname: "Sabrina",
		lastname: "MEJRI",
		desc: "Je fais de mon mieux pour avancer chaque jour",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "sabrina.169@hotmail.fr",
		github: "https://github.com/sab-stack",
		linkedin: "https://www.linkedin.com/in/sabrina-mejri-7880b632b/",
	},
	{
		firstname: "Benoît",
		lastname: "VANDANJON",
		desc: "Formateur de la meilleure promo !",
		skills: [
			{
				manger: "fa-solid fa-utensils",
			},
		],
		email: "benoit@vandanjon.fr",
		github: "https://github.com/Vandanjon",
		linkedin: "https://www.linkedin.com/in/benoitvandanjon/",
	},
	{
		img: "./public/img/img-wilders/flavien.jpg",
		firstname: "Flavien",
		lastname: "ROUSSEAU",
		desc: "Motivaquoi ?",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "Flavien085@gmail.com",
		github: "https://github.com/Foxrim",
		linkedin: "https://www.linkedin.com/in/flavien-rousseau-444bbb199/",
	},
	{
		img: "./public/img/img-wilders/penelope.jpg",
		firstname: "Pénélope",
		lastname: "TEXEIRA",
		desc: "",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "penelope.teix@gmail.com",
		github: "https://github.com/Pene891",
		linkedin: "www.linkedin.com/in/pennyteixeira",
	},
	{
		img: "./public/img/img-wilders/marvin.jpg",
		firstname: "Marvin",
		lastname: "CALMO",
		desc: "",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "calmomarvin93@gmail.com",
		github: "https://github.com/Marvin97120",
		linkedin: "https://www.linkedin.com/in/marvin-calmo-045571333/",
	},
	{
		img: "./public/img/img-wilders/aurelia.jpg",
		firstname: "Aurélia",
		lastname: "GUARINO",
		desc: "Je suis plus passionnée que jamais par le fait de pouvoir donner vie au design de mes maquettes grâce à mes compétences techniques.",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
				figma: "fa-brands fa-figma",
			},
		],
		email: "aureliaguarino@icloud.com",
		github: "https://github.com/oriorinomi",
		linkedin: "https://www.linkedin.com/in/aurélia-guarino-4778b5185/",
	},
	{
		img: "./public/img/img-wilders/jeremy-p.jpg",
		firstname: "Jeremy",
		lastname: "PEREZ",
		desc: "Curieux et motivé, j'adore chercher mes erreurs de typo !",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "jeremy.perez.web@gmail.com",
		github: "https://github.com/JeremyPerezGit",
		linkedin: "",
	},
	{
		img: "./public/img/img-wilders/jeremy-t.jpg",
		firstname: "Jérémy",
		lastname: "TICHANÉ",
		desc: "",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "creamedoc@gmail.com",
		github: "",
		linkedin: "",
	},
	{
		img: "./public/img/img-wilders/maxence.jpg",
		firstname: "Maxence",
		lastname: "CHOISELLE",
		desc: "Je sens bien que vous essayez de me dire quelque chose..",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "mchoiselle@gmail.com",
		github: "https://github.com/Max-10101",
		linkedin: "",
	},
	{
		img: "./public/img/img-wilders/laure.jpg",
		firstname: "Laure",
		lastname: "MAFFINI",
		desc: "Déterminée à faire bouger les lignes !",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "lauremaffini@gmail.com",
		github: "https://github.com/Leslaures",
		linkedin: "https://www.linkedin.com/in/laure-maffini-9368b4139/",
	},
	{
		img: "./public/img/img-wilders/vincent.png",
		firstname: "Vincent",
		lastname: "CHING",
		desc: "Curieux, motivé et passionné par le monde de la tech, j'adore les challenges",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "vincent-ching_student2024@wilder.school",
		github: "https://github.com/Vincent-Ching",
		linkedin: "https://www.linkedin.com/in/vincent-ching-955522109",
	},
	{
		img: "",
		firstname: "Mateusz",
		lastname: "PLEBANEK",
		desc: "",
		skills: "",
		email: "",
		github: "",
		linkedin: "",
	},
	{
		img: "./public/img/img-wilders/raphael.png",
		firstname: "Raphaël",
		lastname: "RIVIÈRE",
		desc: "Curieux et toujours motivé pour apprendre de nouvelles choses et compétences.",
		skills: [
			{
				html: "fa-brands fa-html5",
				css: "fa-brands fa-css3-alt",
				javascript: "fa-brands fa-js",
			},
		],
		email: "raphaelriviere87@gmail.com",
		github: "https://github.com/rrczt974",
		linkedin: "https://www.linkedin.com/in/rivière-raphaël-130b78151/",
	},
];
