const wildersList = [
	{
      img: "./public/img/img-wilders/maxime.png",
		firstname: "Maxime",
		lastname: "TRICOCHE",
		desc: "Persévérant et curieux, je suis toujours désireux d'acquérir de nouvelles compétences",
		skills: [{
         html: "fa-brands fa-html5",
         css: "fa-brands fa-css3-alt",
         javascript: "fa-brands fa-js",
      }
      ],
		email: "maxime.trche@gmail.com",
		github: "https://github.com/maximetricoche",
		linkedin: "https://www.linkedin.com/in/maxime-tricoche-a85142310/",
	},
   {
      img: "./public/img/img-wilders/alexandre.jpg",
      fistname: "Alexandre",
      lastname: "HIANCE",
      desc: "La meilleure façon de produire l'avenir est de le créer. - A. Lincoln",
      skills: "",
      email: "alexandrehiance@gmail.com",
      github: "https://github.com/Alexhian",
      linkedin: "https://www.linkedin.com/in/alexandre-hiance-111718151/",
   },
   {
      fistname: "Sabrina",
      lastname: "MEJRI",
      desc: "Je fais de mon mieux pour avancer chaque jour",
      skills: "",
      email: "sabrina.169@hotmail.fr",
      github: "https://github.com/sab-stack",
      linkedin: "https://www.linkedin.com/in/sabrina-mejri-7880b632b/",
   },
   {
      fistname: "Benoît",
      lastname: "VANDANJON",
      desc: "",
      skills: "",
      email: "benoit@vandanjon.fr",
      github: "https://github.com/Vandanjon",
      linkedin: "https://www.linkedin.com/in/benoitvandanjon/",
   },
   {
      img: "./public/img/img-wilders/flavien.jpg",
      fistname: "Flavien",
      lastname: "ROUSSEAU",
      desc: "Motivaquoi ?",
      skills: "",
      email: "Flavien085@gmail.com",
      github: "https://github.com/Foxrim",
      linkedin: "https://www.linkedin.com/in/flavien-rousseau-444bbb199/",
   },
   {
      img: "./public/img/img-wilders/penelope.jpg",
      fistname: "Pénélope",
      lastname: "TEXEIRA",
      desc: "",
      skills: "",
      email: "penelope.teix@gmail.com",
      github: "https://github.com/Pene891",
      linkedin: "www.linkedin.com/in/pennyteixeira",
   },
   {
      fistname: "Marvin",
      lastname: "CALMO",
      desc: "",
      skills: "",
      email: "calmomarvin93@gmail.com",
      github: "https://github.com/Marvin97120",
      linkedin: "https://www.linkedin.com/in/marvin-calmo-045571333/",
   },
   {
      img: "./public/img/img-wilders/aurelia.jpg",
      fistname: "Aurélia",
      lastname: "GUARINO",
      desc: "Je suis plus passionnée que jamais par le fait de pouvoir donner vie au design de mes maquettes grâce à mes compétences techniques.",
      skills: "",
      email: "aureliaguarino@icloud.com",
      github: "https://github.com/oriorinomi",
      linkedin: "https://www.linkedin.com/in/aurélia-guarino-4778b5185/",
   },
   {
      fistname: "",
      lastname: "",
      desc: "",
      skills: "",
      email: "",
      github: "",
      linkedin: "",
   },
   {
      fistname: "",
      lastname: "",
      desc: "",
      skills: "",
      email: "",
      github: "",
      linkedin: "",
   },
   {
      fistname: "",
      lastname: "",
      desc: "",
      skills: "",
      email: "",
      github: "",
      linkedin: "",
   },
   {
      fistname: "",
      lastname: "",
      desc: "",
      skills: "",
      email: "",
      github: "",
      linkedin: "",
   },
   {
      fistname: "",
      lastname: "",
      desc: "",
      skills: "",
      email: "",
      github: "",
      linkedin: "",
   },
   {
      fistname: "",
      lastname: "",
      desc: "",
      skills: "",
      email: "",
      github: "",
      linkedin: "",
   },
   {
      fistname: "",
      lastname: "",
      desc: "",
      skills: "",
      email: "",
      github: "",
      linkedin: "",
   },
];